formats:
  - name: "dc+sd-jwt"
    module: "pyeudiw.sd_jwt.verifier"
    class: "SDJWTVerifier"
  - name: "ldp_vp"
    module: "pyeudiw.openid4vp.presentation_submission"
    class: "LdpVp"
  - name: "jwt_vp_json"
    module: "pyeudiw.openid4vp.presentation_submission"
    class: "JwtVpJson"
  - name: "mso_mdoc"
    module: "pymdoccbor.mdoc.verifier"
    class: "MdocCbor"

MAX_SUBMISSION_SIZE: 4096